images:
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-1.jpg"
    title: "Chris Sierzant Soloing 'Fuzzy Undercling' 5.11b"
    subtitle: "Military Wall, Red River Gorge, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-2.jpg"
    title: "Carl Bakanowski trailrunning through the snow."
    subtitle: "Seneca Park, Louisville, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-3.jpg"
    title: "Joey Kinder making the FA of 'Southern Comfort Right' 5.14b"
    subtitle: "Little River Canyon, AL"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-4.jpg"
    title: "Ruel Lomigo runs up a hill."
    subtitle: "Cherokee Park, Louisville, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-5.jpg"
    title: "Dan Brechner climbs 'Millipede' V5"
    subtitle: "Horse Pens 40, AL"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-6.jpg"
    title: "Two men cycle during the Master Nationals race"
    subtitle: "Cherokee Park, Louisville, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-7.jpg"
    title: "Jason Kehl on 'The Shield' V12 (2nd ascent)"
    subtitle: "Little Rock City, TN"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-8.jpg"
    title: "James Litz making the FA of 'Stankins' V11"
    subtitle: "Dayton Pocket, TN"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-9.jpg"
    title: "Timy Fairfield making the first ascent of 'Covert Methods' V11/12"
    subtitle: "Red River Gorge, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-10.jpg"
    title: "A climbers chalky hands on a boulder."
    subtitle: ""
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-11.jpg"
    title: "Shadow Ayala on 'Cell Block Six' 5.12c"
    subtitle: "Midnight Surf, Muir Valley, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-12.jpg"
    title: "Kyle Fisher climbs 'Ghetto Superstar' V8"
    subtitle: "Horse Pens 40, AL"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-13.jpg"
    title: "Chris Sierzant on 'Cadillac Thrills' V9"
    subtitle: "Horse Pens 40, AL"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-14.jpg"
    title: "Mark Osbourne climbs 'Man with the slow hand' V4"
    subtitle: "Horse Pens 40, AL"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-15.jpg"
    title: "John Keer on 'Window Shopping' 5.12c"
    subtitle: "Socorro, NM"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-16.jpg"
    title: "Zach Sands taking a whipper from the anchors on 'Tuna Town' 5.12d"
    subtitle: "Red River Gorge, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-17.jpg"
    title: "Mark Osbourne climbing on a decaying building on Main St."
    subtitle: "Louisville, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-18.jpg"
    title: "A man mountain bikes on a trail in Cherokee Park"
    subtitle: "Louisville, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-19.jpg"
    title: "Jay Mitchell on an unknown boulder"
    subtitle: "Linville Gorge, NC"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-20.jpg"
    title: "Mark Osbourne bouldering"
    subtitle: "Linville Gorge, NC"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-21.jpg"
    title: "Adam Henry on 'Skywalker' V9"
    subtitle: "Horse Pens 40, AL"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-22.jpg"
    title: "Lindsay Gasch on 'The Comet' V5"
    subtitle: "Rocktown, GA"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-23.jpg"
    title: "Deanna Lombardo on 'Banshee' 5.11c"
    subtitle: "Solarium KY, Muir Valley, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-24.jpg"
    title: "Daniel Brechner skates at the Metro Sewer District Overflow."
    subtitle: "Louisville, KY"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-25.jpg"
    title: "Elizabeth Arce climbs 'The Sherman Photo Roof' problem V7"
    subtitle: "Rocktown, GA"
  - url: "https://s3.amazonaws.com/content.danlubbers.com/img/action/danlubbers-action-portfolio-26.jpg"
    title: "Eric Gifford climbs 'Latin for dagger' V5"
    subtitle: "Little Rock City, TN"
