---
layout: default
---

<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-1.jpg" data-title="Climbers sleep in their tents during a foggy night at Miguel's Pizza." data-subtitle="Red River Gorge, KY" alt="Climbers sleep in their tents during a foggy night at Miguel's Pizza in Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-2.jpg" data-title="A skateboarder scopes out a spot in Butchertown." data-subtitle="Louisville, KY" alt="A skateboarder scopes out a spot in Butchertown, Louisville, KY." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-3.jpg" data-title="Mixed Martial Arts fighter, Eric Gifford faces off his opponent." data-subtitle="Belterra Casino, IN" alt="Mixed Martial Arts fighter, Eric Gifford faces off his opponent at the Belterra Casino, IN." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-4.jpg" data-title="The silhouette of a woman gazes over the Pacific Ocean beneath a tree." data-subtitle="The Big Island of Hawaii" alt="The silhouette of a woman gazes over the Pacific Ocean beneath a tree on The Big Island of Hawaii." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-5.jpg" data-title="A cyclist warms up on a stationary cycling stand before a race." data-subtitle="" alt="A cyclist warms up on a stationary cycling stand before a race." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-6.jpg" data-title="Pro-climber, Jason Kehl warms up the digits in 25 degree weather before hoping back on the rock." data-subtitle="" alt="Pro-climber, Jason Kehl warms up the digits in 25 degree weather before hoping back on the rock at Little Rock City, TN." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-7.jpg" data-title="A man rests with his snowboard atop the mountain." data-subtitle="Max Patch, NC" alt="A man rests with his snowboard atop the mountain on Max Patch, NC." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-8.jpg" data-title="Burgers cooking on a grill during sunset." data-subtitle="" alt="Burgers cooking on a grill during sunset." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-9.jpg" data-title="Shadow Ayala tries to rodeo clip his rope into the quickdraw without using a stickclip." data-subtitle="Red River Gorge, KY" alt="Shadow Ayala tries to rodeo clip his rope into the quickdraw without using a stickclip." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-10.jpg" data-title="Jamie Lang | Lang Art Glass | Working on a smoking pipe." data-subtitle="" alt="Jamie Lang | Lang Art Glass | Working on a smoking pipe." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-11.jpg" data-title="Stephen Woodward takes a day off from rock climbing to enjoy the gorgeous area of Natural Bridge State Park." data-subtitle="Red River Gorge, KY" alt="Stephen Woodward takes a day off from rock climbing to enjoy the gorgeous area of Natural Bridge State Park in Red River Gorge, KY shot for National Geographic Magazine." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-12.jpg" data-title="A cyclist plans his route for an Alley Cat Race." data-subtitle="The Highlands of Louisville, KY" alt="A cyclist plans his route for an Alley Cat Race in the Louisville Highlands, KY." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-13.jpg" data-title="A climber gets their figure eight knot stuck and another person helps to undo the knot." data-subtitle="" alt="A climber gets their figure eight knot stuck and another person helps to undo the knot." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-14.jpg" data-title="A goat eats grass in a field behind Miguel's Pizza." data-subtitle="Red River Gorge, KY" alt="A goat eats grass in a field behind Miguel's Pizza in Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-15.jpg" data-title="Concert goers legs and shadows." data-subtitle="" alt="Concert goers legs and shadows." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-16.jpg" data-title="A crowd of cyclists prepare for an alley cat race." data-subtitle="The Highlands of Louisville, KY" alt="A crowd of cyclists prepare for an alley cat race in the Louisville Highlands." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-17.jpg" data-title="A fan smokes a cigarette near a porta-potty at a music festival." data-subtitle="" alt="A fan smokes a cigarette near a porta-potty at a music festival." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-18.jpg" data-title="Artist Justin Vining paints in his studio." data-subtitle="Indianapolis, IN" alt="Artist Justin Vining paints at Studio 654 in Indianapolis, IN."  />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-19.jpg" data-title="Dario Ventura bolts a new route on a rock wall" data-subtitle="Red River Gorge, KY" alt="Dario Ventura bolts a new route on a rock wall in Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-20.jpg" data-title="A woman plays a guitar." data-subtitle="" alt="A woman plays a guitar." />
<img src="http://content.danlubbers.com/img/lifestyle/danlubbers-lifestyle-portfolio-21.jpg" data-title="A fighter gets his hands wrapped before his match." data-subtitle="" alt="A fighter gets his hands wrapped before his match." />
