---
layout: default
---

<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-1.jpg" data-title="The sun shines through the fog on a highway." data-subtitle="" alt="The sun shines through the fog on a highway." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-2.jpg" data-title="Hawaiian Hibiscus (Hibiscus brackenridgei) is the state flower of Hawaii." data-subtitle="" alt="Hawaiian Hibiscus (Hibiscus brackenridgei) is the state flower of Hawaii." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-3.jpg" data-title="A farm in rural Kentucky grows tobacco." data-subtitle="" alt="A farm in rural Kentucky grows tobacco." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-4.jpg" data-title="Akaka waterfall" data-subtitle="Akaka State Falls Park, HI" alt="Akaka waterfall at Akaka State Falls Park, HI." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-5.jpg" data-title="A lightning storms rolls through Louisville, KY." data-subtitle="" alt="A lightning storms rolls through Louisville, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-6.jpg" data-title="A silhouetted girl stands on a pier watching the sun set." data-subtitle="Ohio River, Westport, KY" alt="A silhouetted girl stands on a pier watching the sun set in Westport, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-7.jpg" data-title="The summit of Mauna Kea at 4000m" data-subtitle="The Big Island of Hawaii" alt="The summit of Mauna Kea at 4000m on The Big Island of Hawaii." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-8.jpg" data-title="A barge passes by downtown Louisville , KY as it moves south along the Ohio River." data-subtitle="" alt="A barge passes by downtown Louisville , KY as it moves south along the Ohio River." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-9.jpg" data-title="Weeds, trees and sky." data-subtitle="" alt="Weeds, trees and sky." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-10.jpg" data-title="The Pu u Loa Petroglyphs." data-subtitle="Volcanoes National Park, HI" alt="The Pu u Loa Petroglyphs at Volcanoes National Park, HI." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-11.jpg" data-title="A scope on a sniper rifle." data-subtitle="" alt="A scope on a sniper rifle." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-12.jpg" data-title="Chimney top rock" data-subtitle="Red River Gorge, KY" alt="Chimney top rock in Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-13.jpg" data-title="A windfarm in Northern Indiana." data-subtitle="" alt="A windfarm in Northern Indiana." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-14.jpg" data-title="Feet on a Prana yoga mat." data-subtitle="" alt="Feet on a Prana yoga mat." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-15.jpg" data-title="Puscifer band members Carina Round and Maynard James Keenan perform." data-subtitle="The Brown in Louisville, KY" alt="Puscifer band members Carina Round and Maynard James Keenan perform at The Brown in Louisville, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-16.jpg" data-title="The sun sets at the Falls of the Ohio." data-subtitle="" alt="The sun sets at the Falls of the Ohio." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-17.jpg" data-title="Frosted Lambs ear (Stachys byzantina) on a winter morning in Kentucky." data-subtitle="" alt="Frosted Lambs ear (Stachys byzantina) on a winter morning in Kentucky." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-18.jpg" data-title="Observatories sit atop Mauna Kea on the Big Island of Hawaii." data-subtitle="" alt="Observatories sit atop Mauna Kea on the Big Island of Hawaii overlooking the Pacific ocean at 4000m with Maui in the distance." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-19.jpg" data-title="Silhouette of a tree just after a storm at sunset" data-subtitle="Kansas City, MO" alt="Silhouette of a tree just after a storm at sunset in Kansas City, MO." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-20.jpg" data-title="A dead end sign with bullet holes in the woods." data-subtitle="Red River Gorge, KY" alt="A dead end sign with bullet holes in the woods in Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-21.jpg" data-title="Dormant Volcano cones | 4000m/13,796ft" data-subtitle="Mauna Kea Summit, HI" alt="Dormant Volcano cones | 4000m/13,796ft atop the summit of Mauna Kea, HI." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-22.jpg" data-title="A raging bonfire keeps the climbers warm at Miguel's Pizza." data-subtitle="Red River Gorge, KY" alt="A raging bonfire keeps the climbers warm at Miguel's Pizza in the Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-23.jpg" data-title="Afternoon nap in my hammock at a cliff" data-subtitle="Red River Gorge, KY" alt="Afternoon nap in my hammock at a cliff in the Red River Gorge, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-24.jpg" data-title="An evergreen tree" data-subtitle="Interlochen, MI" alt="An evergreen tree in Interlochen, MI." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-25.jpg" data-title="The sun beams through trees" data-subtitle="Cherokee Park, Louisville, KY" alt="The sun beams through trees at Cherokee Park in Louisville, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-26.jpg" data-title="The sun sets on the Ohio River at a pier" data-subtitle="Louisville, KY" alt="The sun sets on the Ohio River at a pier in Louisville, KY." />
<img src="http://content.danlubbers.com/img/iphoneography/danlubbers-iphoneography-portfolio-27.jpg" data-title="An airplane in the sky." data-subtitle="" alt="An airplane in the sky." />
